let suggestions = [
    "Aarão Reis",
    "Acaba Mundo",
    "Acaba Mundo",
    "Ademar Maldonado",
    "Aeroporto",
    "Alípio de Melo",
    "Alto Barroca",
    "Alto dos Pinheiros",
    "Alto Vera Cruz",
    "Álvaro Camargos",
    "Alvorada",
    "Ana Lúcia",
    "Ana Lúcia de Cássia",
    "Anchieta",
    "Antônio Ribeiro de Abreu",
    "Aparecida  (Barreiro)",
    "Aparecida (Venda Nova)",
    "Aparecida da Lagoa",
    "Aparecida do Norte",
    "Aparecida do Sul",
    "Arapoã",
    "Área Hospitalar",
    "Armênia",
    "Arteiro",
    "Atalaia",
    "Bairro das Indústrias I",
    "Bairro das Indústrias II",
    "Bairro dos Funcionários",
    "Bairro Independência",
    "Bairro Novo das Indústrias",
    "Bandeirantes",
    "Bandeirinhas",
    "Barão Homem de Melo",
    "Barcelona",
    "Barreiro",
    "Barro Preto",
    "Bela Vista",
    "Belmonte",
    "Bernardo Monteiro",
    "Betânia",
    "Boa Esperança",
    "Boa Viagem",
    "Boa Vista (Norte)",
    "Boa Vista (Pampulha)",
    "Bom Jesus",
    "Bom Pastor",
    "Bonfim",
    "Bonsucesso",
    "Brasil Industrial",
    "Cachoeirinha",
    "Caiçara",
    "Califórnia",
    "Camargos",
    "Camilo Alves",
    "Campina Verde",
    "Campo Alegre",
    "Canaã",
    "Candelária",
    "Capitão Eduardo",
    "Capitão Eduardo",
    "Cardoso",
    "Carlos Prates",
    "Carmo",
    "Casa Branca",
    "Casa Grande",
    "Castanheira",
    "Castelo",
    "Centenário",
    "Céu Azul",
    "Chácara",
    "Chácara Boa Vista",
    "Chácara Dona Clara",
    "Chácara Leblon",
    "Cidade Industrial",
    "Cidade Industrial",
    "Cidade Jardim",
    "Cidade Jardim Taquaril",
    "Cidade Nova",
    "Cidade Nova",
    "Cidade Nova",
    "Cidade Nova",
    "Cidade Universitária",
    "Cláudia",
    "Colégio Batista",
    "Comiteco",
    "Confisco",
    "Conjunto Águas Brancas",
    "Conjunto Felicidade",
    "Conjunto Jaqueline",
    "Conjunto Minas Caixa",
    "Conjunto Taquaril",
    "Conjunto Várzea da Palma",
    "Copacabana",
    "Copacabana",
    "Coqueiros",
    "Coração Eucarístico",
    "Corumbiara",
    "Cruzeiro",
    "Cruzeiro do Sul",
    "Diamante",
    "Dom Bosco",
    "Dom Cabral",
    "Dom Joaquim",
    "Dom Orione",
    "Dom Silvério",
    "Dom Silvério",
    "Dona Clara",
    "Dona Rosarinha",
    "Durval de Barros",
    "Durval de Barros",
    "Eldorado",
    "Engenho Nogueira",
    "Belo Horizonte",
    "Uberlândia",
    "Contagem",
    "Betim",
    "Juiz de Fora",
    "Montes Claros",
    "Ribeirão das Neves",
    "Uberaba",
    "Governador Valadares",
    "Ipatinga",
];